# Generated by Django 6.0.5 on 2026-05-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='trans_type',
        ),
    ]
