# Generated by Django 6.0.5 on 2026-06-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_supportrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Income', 'Income'), ('Mandatory Expenses', 'Mandatory Expenses'), ('Maintenance', 'Maintenance'), ('Unexpected Expenses', 'Unexpected Expenses'), ('Education', 'Education'), ('Food', 'Food'), ('Transportation', 'Transportation'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Household', 'Household'), ('Healthcare', 'Healthcare'), ('Personal Care', 'Personal Care'), ('Communication', 'Communication'), ('Subscriptions', 'Subscriptions'), ('Entertainment', 'Entertainment'), ('Investment', 'Investment'), ('Business Related', 'Business Related'), ('Family Support', 'Family Support'), ('Pets', 'Pets'), ('Donations', 'Donations'), ('Bank Charges', 'Bank Charges'), ('Miscellaneous', 'Miscellaneous')], max_length=100),
        ),
    ]
