# Generated by Django 6.0.5 on 2026-07-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_supportrequest_status_userprofile_savingsgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='goal_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
