# Generated by Django 6.0.5 on 2026-08-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_transaction_user_category_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_description', models.CharField(help_text='Raw transaction string as entered by the user or imported.', max_length=500)),
                ('normalized_description', models.CharField(db_index=True, help_text='TextNormalizer output — used for deduplication lookups.', max_length=500)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('frequency', models.PositiveIntegerField(default=1, help_text='How many times this normalized description was logged.')),
            ],
            options={
                'verbose_name': 'Unknown Transaction',
                'verbose_name_plural': 'Unknown Transactions',
                'ordering': ['-frequency', '-last_seen'],
            },
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='expenses_tr_user_id_9b966f_idx',
            old_name='expenses_tr_user_id_category_idx',
        ),
        migrations.AddIndex(
            model_name='unknowntransaction',
            index=models.Index(fields=['normalized_description'], name='expenses_un_normali_e79464_idx'),
        ),
        migrations.AddIndex(
            model_name='unknowntransaction',
            index=models.Index(fields=['frequency'], name='expenses_un_frequen_4de8c1_idx'),
        ),
    ]
